apps/library/urls.py
from django.urls import re_path
from .views import *

urlpatterns = [
    re_path(
        route=r'^(?P<page>\d*)?/?$',
        view=BookListView.as_view(),
        name='book_list'
    ),
    re_path(
        route=r'^tag/(?P<tag>\d+)/(?P<page>\d*)?/?$',
        view=TagBookListView.as_view(),
        name='tag_book_list'
    ),
    re_path(
        route=r'^book/(?P<pk>\d+)/$',
        view=BookDetailView.as_view(),
        name='book_detail'
    ),
    re_path(
        route=r'^book/(?P<pk>\d+)/edit/$',
        view=BookUpdateView.as_view(),
        name='book_edit'
    ),
    re_path(
        route=r'^book/add/$',
        view=BookCreateView.as_view(),
        name='book_create'
    ),
    re_path(
        route=r'^book/(?P<pk>\d+)/delete/$',
        view=BookDeleteView.as_view(),
        name='book_delete'
    ),
    re_path(
        route=r'^comment/(?P<pk>\d+)/delete/$',
        view=CommentDeleteView.as_view(),
        name='comment_delete'
    ),
    re_path(
        route=r'^statistics/$',
        view=StatisticsView.as_view(),
        name='statistics'
    )
]

apps/personal_area/urls.py
from django.urls import re_path
from .views import *


urlpatterns = [
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),
    re_path(r'^registration/$', RegistrationView.as_view(), name='registration'),
    re_path(r'^profile/$', ProfileView.as_view(), name='profile_detail'),
    re_path(r'^profile/edit/$', ProfileUpdateView.as_view(), name='profile_update'),
    # url(r'^profile/edit/$', UserUpdateView.as_view(), name='profile_update'),
]

urls.py
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    re_path(r'^', include(('apps.blog.urls', 'blog'), namespace='blog')),
    re_path(r'^', include(('apps.personal_area.urls', 'personal_area'), namespace='personal_area')),
    path("films/", include(('apps.films.urls', 'films'), namespace='films')),
    re_path(r'^library/', include(('apps.library.urls', 'library'), namespace='library')),
    re_path(r'^summernote/', include('django_summernote.urls')),
    re_path(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/library/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse
from django.templatetags.static import static
from django.utils.safestring import mark_safe
from django.core.files.uploadedfile import SimpleUploadedFile
from PIL import Image
import io
import os


FILE_FORMATS = (
    (0, 'PDF'),
    (1, 'DJVU'),
)

BACKGROUND_COLORS = (
    ("bgm-white", "White"),
    ("bgm-black", "Black"),
    ("bgm-brown", "Brown"),
    ("bgm-pink", "Pink"),
    ("bgm-red", "Red"),
    ("bgm-blue", "Blue"),
    ("bgm-purple", "Purple"),
    ("bgm-deeppurple", "Deep purple"),
    ("bgm-lightblue", "Light blue"),
    ("bgm-cyan", "Cyan"),
    ("bgm-teal", "Teal"),
    ("bgm-green", "Green"),
    ("bgm-lightgreen", "Light green"),
    ("bgm-lime", "Lime"),
    ("bgm-yellow", "Yellow"),
    ("bgm-amber", "Amber"),
    ("bgm-orange", "Orange"),
    ("bgm-deeporange", "Deep orange"),
    ("bgm-gray", "Gray"),
    ("bgm-bluegray", "Blue gray"),
    ("bgm-indigo", "Indigo"),
)


class Book(models.Model):
    title = models.CharField(verbose_name="Название", max_length=500)
    description = models.TextField(verbose_name="Описание", blank=True)
    cover = models.ImageField(verbose_name="Обложка", blank=True, upload_to='library/covers')
    cover_thumbnail = models.ImageField(verbose_name="Превью", blank=True, upload_to='library/thumbnails')
    authors = models.ManyToManyField(verbose_name="Авторы", to='Author', blank=True)
    publishers = models.ManyToManyField(verbose_name="Издательства", to='Publisher')
    year = models.PositiveIntegerField(verbose_name="Год издания")
    tags = models.ManyToManyField(verbose_name="Теги", to='Tag', blank=True)
    page_count = models.PositiveSmallIntegerField(verbose_name="Количество страниц", default=0)
    draft = models.BooleanField(verbose_name="Черновик", default=False)
    created_date = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)
    changed_date = models.DateTimeField(verbose_name="Дата последнего изменения", auto_now=True)
    url = models.URLField(verbose_name='Ссылка для скачивания')
    size = models.FloatField(verbose_name='Размер файла', help_text='Условный размер файла в мегабайтах')
    format = models.PositiveSmallIntegerField(verbose_name='Формат файла', choices=FILE_FORMATS, default=0)

    likes = GenericRelation(to='personal_area.Like', related_query_name='books')
    comments = GenericRelation(to='personal_area.Comment', related_query_name='books')

    def create_thumbnail(self):
        """Метод создания миниатюрной обложки для книги"""
        if not self.cover:  # Если обложки нет, то и создавать миниатюру не нужно
            return

        # Если миниатюра уже была создана ранее, то её необходимо удалить
        old_file = self.cover_thumbnail
        if old_file and os.path.isfile(old_file.path):
            os.remove(old_file.path)

        image = Image.open(io.BytesIO(self.cover.read()))
        image.thumbnail(size=(256, image.height), resample=Image.ANTIALIAS)
        temp_handle = io.BytesIO()
        image.save(temp_handle, format='png')
        temp_handle.seek(0)
        suf = SimpleUploadedFile(os.path.split(self.cover.name)[-1], temp_handle.read(), content_type='image/png')
        file_name = '{0}.png'.format(os.path.splitext(suf.name)[0])
        self.cover_thumbnail.save(name=file_name, content=suf, save=False)
        temp_handle.close()

    def save(self, *args, **kwargs):
        self.create_thumbnail()
        super(Book, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('library:book_detail', args=(self.id,))

    def get_cover_url(self):
        if self.cover:
            return self.cover.url
        return static('img/missing_book_cover.jpg')

    def get_cover_thumbnail_url(self):
        if self.cover_thumbnail:
            return self.cover_thumbnail.url
        return static('img/missing_book_cover.jpg')

    def get_cover(self):
        img_html_tag = '<img src="%s" width="50px">' % self.get_cover_thumbnail_url()
        return mark_safe(img_html_tag)

    get_cover.short_description = "Обложка"

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-id',)
        verbose_name = "Книга"
        verbose_name_plural = "Книги"


class Author(models.Model):
    full_name = models.CharField(verbose_name='Полное имя', max_length=255)

    def __str__(self):
        return self.full_name

    class Meta:
        ordering = ('full_name',)
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'


class Publisher(models.Model):
    name = models.CharField(verbose_name='Название', max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Издательство'
        verbose_name_plural = 'Издательства'


class Tag(models.Model):
    name = models.CharField(verbose_name='Название', max_length=255)
    color = models.CharField(verbose_name="Цвет", max_length=20, choices=BACKGROUND_COLORS, default='bgm-gray')

    def get_absolute_url(self):
        return reverse('library:tag_book_list', args=(self.id,))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

apps/library/forms.py
from django import forms
from django.forms import inlineformset_factory
from django_summernote.widgets import SummernoteWidget
from .models import Book, Author, Publisher, Tag


class BookForm(forms.ModelForm):
    authors_list = forms.CharField(label="Список авторов", help_text="Введите авторов через запятую", required=False,
                                   widget=forms.TextInput(attrs={'class': 'uk-input uk-form-width-large'}))

    def save(self, commit=True):
        book = super().save(commit=commit)
        # Добавление авторов перечисленных в текстовом поле через запятую
        authors_list = self.cleaned_data.get('authors_list', '').split(',')
        authors_list = filter(None, [author.strip() for author in authors_list])
        for author_fullname in authors_list:
            author = Author.objects.get_or_create(full_name=author_fullname)[0]
            book.authors.add(author)
        return book

    class Meta:
        model = Book
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'uk-input uk-form-width-large'}),
            'description': SummernoteWidget(),
            'year': forms.TextInput(attrs={'class': 'uk-input uk-form-width-large'}),
            'authors': forms.SelectMultiple({'class': 'uk-select uk-form-width-large'}),
            'publishers': forms.SelectMultiple({'class': 'uk-select uk-form-width-large'}),
            'category': forms.Select({'class': 'uk-select uk-form-width-large'}),
            'tags': forms.SelectMultiple({'class': 'uk-select uk-form-width-large'}),
            'page_count': forms.NumberInput({'class': 'uk-input uk-form-width-large'}),
            'url': forms.URLInput({'class': 'uk-input uk-form-width-large'}),
            'size': forms.NumberInput({'class': 'uk-input uk-form-width-large'}),
            'format': forms.Select({'class': 'uk-select uk-form-width-large'}),
        }


class BookFilterForm(forms.Form):
    author_id = forms.MultipleChoiceField(label='Автор')
    publisher_id = forms.MultipleChoiceField(label='Издательство')
    tag_id = forms.MultipleChoiceField(label='Тэг', widget=forms.CheckboxSelectMultiple())

    def __init__(self, **kwargs):
        super(BookFilterForm, self).__init__(**kwargs)
        for field_name in self.fields:  # Делаем все поля необязательными
            self.fields[field_name].required = False
        self.fields['author_id'].choices = [(x.id, x.full_name) for x in Author.objects.all()]
        self.fields['publisher_id'].choices = [(x.id, x.name) for x in Publisher.objects.all()]
        self.fields['tag_id'].choices = [(x.id, x.name) for x in Tag.objects.all()]


class BookAdminForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        widgets = {
            'description': SummernoteWidget(),
        }

apps/library/views.py
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView, TemplateView
from django.views.generic.edit import FormMixin, ProcessFormView
from django.contrib.auth.mixins import UserPassesTestMixin, PermissionRequiredMixin
from django_filters.views import FilterMixin
from django.db.models import Max, Min, Avg, Sum, Count

from apps.personal_area.forms import CommentForm
from apps.personal_area.models import Comment
from .filtersets import BookFilterSet
from .models import *
from .forms import *


class BookListView(FilterMixin, ListView):
    template_name = 'library/book_list.html'
    model = Book
    paginate_by = 16
    filterset_class = BookFilterSet

    def get_queryset(self):
        qs = super(BookListView, self).get_queryset().filter(draft=False)
        qs = qs.annotate(Count('likes'), Count('comments'))
        return qs

    def get_context_data(self, **kwargs):
        filterset = self.get_filterset(self.get_filterset_class())
        kwargs['filter'] = filterset
        kwargs['object_list'] = filterset.qs
        return super().get_context_data(**kwargs)


class TagBookListView(BookListView):
    template_name = 'library/book_list_tag.html'
    category = None

    def get_queryset(self):
        queryset = super(TagBookListView, self).get_queryset()
        self.tag = Tag.objects.get(id=self.kwargs.get('tag'))
        queryset = queryset.filter(tags=self.tag)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(TagBookListView, self).get_context_data(**kwargs)
        context['tag'] = self.tag
        return context


class BookDetailView(DetailView, UserPassesTestMixin, ProcessFormView, FormMixin):
    template_name = 'library/book_detail.html'
    model = Book
    form_class = CommentForm

    def test_func(self):
        is_draft = self.get_object().draft
        is_superuser = self.request.user.is_superuser
        condition = not is_draft or (is_draft and is_superuser)
        return condition

    def get_success_url(self):
        return self.get_object().get_absolute_url()

    def form_valid(self, form):
        obj = self.get_object()
        comment = form.save(commit=False)
        comment.content_object = obj
        comment.author = self.request.user
        comment.save()
        return super(BookDetailView, self).form_valid(form)


class BookUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'library/book_update.html'
    model = Book
    form_class = BookForm
    permission_required = ['library.change_book']


class BookCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'library/book_create.html'
    model = Book
    form_class = BookForm
    permission_required = ['library.add_book']


class BookDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'library/book_delete.html'
    model = Book
    permission_required = ['library.delete_book']

    def get_success_url(self):
        return reverse('library:book_list')


class CommentDeleteView(UserPassesTestMixin, DeleteView):
    model = Comment

    def test_func(self):
        if self.get_object().author == self.request.user or self.request.user.is_superuser:
            return True
        return False

    def get_success_url(self):
        obj = self.get_object()
        return reverse('library:book_detail', args=(obj.content_object.id,))


class StatisticsView(TemplateView):
    template_name = 'library/statistics.html'

    def get_context_data(self, **kwargs):
        context = super(StatisticsView, self).get_context_data(**kwargs)

        size_queryset = Book.objects.order_by('size').values_list('size', 'title')
        context['size_labels'] = [book[1] for book in size_queryset]
        context['size_values'] = [book[0] for book in size_queryset]

        page_queryset = Book.objects.order_by('page_count').values_list('page_count', 'title')
        context['page_count_labels'] = [book[1] for book in page_queryset]
        context['page_count_values'] = [book[0] for book in page_queryset]

        return context

apps/library/templates/library/book_detail.html
{% extends 'base.html' %}
{% load static %}
{% load library_template_tags %}

{% block breadcrumb %}
    <li><a href="{% url 'library:book_list' %}">Все книги</a></li>
    <li><span>{{ book.title }}</span></li>
{% endblock %}

{% block content %}
    <div uk-grid>
        <div class="uk-width-expand@m">
            <div class="uk-card uk-card-default">
                <div class="uk-card-header">
                    <div class="uk-grid-small uk-flex-middle" uk-grid>
                        <div class="uk-width-expand">
                            <h3 class="uk-card-title uk-margin-remove-bottom">{{ book.title }}</h3>
                            <p class="uk-text-meta uk-margin-remove-top">
                                <time datetime="2016-04-01T19:00">{{ book.create_date }}</time>
                            </p>
                        </div>
                        <div class="uk-width-auto">
                            <a uk-icon="more-vertical"></a>
                            <div uk-dropdown="mode: click; pos: bottom-right; duration: 100">
                                <ul class="uk-nav uk-dropdown-nav uk-iconnav uk-iconnav-vertical">
                                    <li>
                                        <a href="{% url 'library:book_edit' book.id %}">
                                            <span uk-icon="file-edit" class="uk-margin-small-right"></span>
                                            Редактировать
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'library:book_delete' book.id %}">
                                            <span uk-icon="trash" class="uk-margin-small-right"></span>
                                            Удалить
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="uk-card-body">
                    <div uk-grid>
                        <div class="uk-width-1-4@m">
                            <div uk-lightbox>
                                <a href="{{ book.get_cover_url }}" data-caption="{{ book.title }}">
                                    <img src="{{ book.get_cover_thumbnail_url }}">
                                </a>
                            </div>
                        </div>
                        <div class="uk-width-expand@m">
                            <div class="uk-grid-small" uk-grid>
                                <div class="uk-width-expand" uk-leader>
                                    <b>Авторы</b>
                                </div>
                                <div>
                                    {{ book.authors.all|join:', ' }}
                                </div>
                            </div>
                            <div class="uk-grid-small" uk-grid>
                                <div class="uk-width-expand" uk-leader>
                                    <b>Издательства</b>
                                </div>
                                <div>
                                    {{ book.publishers.all|join:', ' }}
                                </div>
                            </div>
                            <div class="uk-grid-small" uk-grid>
                                <div class="uk-width-expand" uk-leader>
                                    <b>Год издания</b>
                                </div>
                                <div>
                                    {{ book.year }}
                                </div>
                            </div>
                            <div class="uk-grid-small" uk-grid>
                                <div class="uk-width-expand" uk-leader>
                                    <b>Количество страниц</b>
                                </div>
                                <div>
                                    {{ book.page_count }}
                                </div>
                            </div>
                            <p>
                                {{ book.description|safe }}
                            </p>
                            {% if not request.user.is_anonymous %}
                                <b>Ссылки для скачивания</b>
                                <br>
                                <a href="{{ book.url }}" target="_blank" class="book-file-link">
                                    {{ book.url }}
                                    <span uk-icon="link"></span>
                                </a>
                                {{ book.size }} mb ({{ book.get_format_display }})
                            {% else %}
                                <b>
                                    Для скачивания файла необходимо
                                    <a href="{% url 'personal_area:login' %}?next={% url 'library:book_detail' book.id %}">авторизоваться</a>
                                    или
                                    <a href="{% url 'personal_area:registration' %}">зарегистрироваться</a>
                                </b>
                            {% endif %}
                            {% if book.tags.exists %}
                                <p>
                                    {% for tag in book.tags.all %}
                                        <span class="tag {{ tag.color }}">{{ tag }}</span>
                                    {% endfor %}
                                </p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="uk-card-footer">
                    {% for like in book.likes.all %}
                        <img class="small-avatar uk-border-circle" src="{{ like.user.profile.get_photo_url }}">
                    {% endfor %}
                </div>
            </div>

            <ul class="uk-comment-list  uk-padding-small">
                {% for comment in book.comments.all %}
                    <li id="comment-{{ comment.id }}">
                        <div class="uk-comment uk-visible-toggle" tabindex="-1">
                            <header class="uk-comment-header uk-position-relative">
                                <div class="uk-grid-medium uk-flex-middle" uk-grid>
                                    <div class="uk-width-auto">
                                        <img class="uk-comment-avatar uk-border-circle medium-avatar"
                                             src="{{ comment.author.profile.get_photo_url }}"
                                             width="80" height="80" alt="">
                                    </div>
                                    <div class="uk-width-expand">
                                        <h4 class="uk-comment-title uk-margin-remove">
                                            <a class="uk-link-reset" href="#">{{ comment.author }}</a>
                                        </h4>
                                        <p class="uk-comment-meta uk-margin-remove-top">
                                            <a class="uk-link-reset" href="#">{{ comment.creation_date }}</a>
                                        </p>
                                    </div>
                                </div>
                                {% if comment.author == request.user or request.user.is_superuser %}
                                    <div class="uk-position-top-right uk-position-small uk-hidden-hover">
                                        <form method="post" action="{% url 'library:comment_delete' comment.id %}">
                                            {% csrf_token %}
                                            <button class="uk-link-muted uk-button uk-button-text">
                                                Удалить
                                            </button>
                                        </form>
                                    </div>
                                {% endif %}
                            </header>
                            <div class="uk-comment-body">
                                {{ comment.text }}
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            {% if not request.user.is_anonymous %}
                <form method="post">
                    {% csrf_token %}
                    <div class="uk-margin">
                        {{ form.text }}
                    </div>
                    <button type="submit" class="uk-button uk-button-primary">
                        Отправить
                    </button>
                </form>
            {% endif %}
        </div>
        <div class="uk-width-1-3@m">
            {% include_library_main_sidebar %}
        </div>
    </div>
{% endblock %}

apps/library/templates/library/book_list.html
{% extends 'base.html' %}
{% load static %}
{% load library_template_tags %}

{% block breadcrumb %}
    <li><span>Все книги</span></li>
{% endblock %}

{% block content %}
    <div class="uk-child-width-expand" uk-grid>
        <div>
            <div class="uk-grid-small" uk-grid uk-height-match="target: > div > .uk-card > .uk-card-body">
                {% for book in book_list %}
                    <div class="uk-width-1-4@l">
                        <div class="uk-card uk-card-default uk-card-small">
                            <div class="uk-card-media-top">
                                <img src="{{ book.get_cover_thumbnail_url }}" width="100%" alt="">
                            </div>
                            <div class="uk-card-header">
                                <div uk-grid>
                                    <div class="uk-width-expand">
                                        <div class="uk-text-meta">
                                            <span uk-icon="icon:heart; ratio:0.7"></span>
                                            {{ book.likes__count }}
                                            &nbsp;
                                            <span uk-icon="icon:comment; ratio:0.7"></span>
                                            {{ book.comments__count }}
                                        </div>
                                    </div>
                                    <div class="uk-width-auto">
                                        <a uk-icon="icon:more-vertical; ratio:0.7"></a>
                                        <div uk-dropdown="mode: click; pos: bottom-right; duration: 100">
                                            <ul class="uk-nav uk-dropdown-nav">
                                                <li>
                                                    <a href="{{ book.get_absolute_url }}">
                                                        <span uk-icon="file" class="uk-margin-small-right"></span>
                                                        Просмотреть
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="{% url 'library:book_edit' book.id %}">
                                                        <span uk-icon="file-edit" class="uk-margin-small-right"></span>
                                                        Редактировать
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="{% url 'library:book_delete' book.id %}">
                                                        <span uk-icon="trash" class="uk-margin-small-right"></span>
                                                        Удалить
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="uk-card-body">
                                <span class="">{{ book.title }}</span>
                            </div>
                            <div class="uk-card-footer">
                                <div uk-grid>
                                    <div class="uk-width-expand uk-flex uk-flex-right">
                                        <a href="{{ book.get_absolute_url }}" class="uk-button uk-button-link">
                                            Read more
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="uk-text-center uk-card uk-card-default uk-card-body uk-width-expand">
                        Пусто
                    </div>
                {% endfor %}
            </div>
            {% block pagination %}
                {% include 'library/pagination.html' %}
            {% endblock %}
        </div>
        <div class="uk-width-1-3@m">
            <div grid>
                {% include_library_main_sidebar %}
                {% include 'library/filter_form.html' with form=filter.form %}
            </div>
        </div>
    </div>
{% endblock %}

apps/library/templates/library/category_sidebar.html
<div class="uk-card uk-card-default uk-margin">
    <div class="uk-card-header">
        <div uk-grid>
            <div class="uk-width-expand">
                <h3 class="uk-card-title uk-margin-remove-bottom">Категории</h3>
            </div>
        </div>
    </div>
    <div class="uk-card-body">
        <ul>
            <li>
                <a href="{% url 'library:book_list' %}">Все книги</a>
                <span class="uk-text-meta">{{ books_count }}</span>
            </li>
            {% for category in categories %}
                <li>
                    <a href="{{ category.get_absolute_url }}">{{ category }}</a>
                    <span class="uk-text-meta">{{ category.book_set.count }}</span>
                </li>
            {% endfor %}
            <li>
                <a href="{% url 'library:category_book_list' 'none' %}">Без категории</a>
                <span class="uk-text-meta">{{ books_without_category_count }}</span>
            </li>
        </ul>
    </div>
    <div class="uk-card-footer">
        <div uk-grid>
            <div class="uk-width-expand">
                <a href="{% url 'library:book_create' %}" class="uk-button uk-button-default">Добавить книгу</a>
            </div>
        </div>
    </div>
</div>

apps/library/templates/library/main_sidebar.html
<div class="uk-card uk-card-default uk-margin">
    <div class="uk-card-header">
        <div class="uk-grid-small uk-flex-middle" uk-grid>
            <div class="uk-width-expand">
                <h3 class="uk-card-title uk-margin-remove-bottom">Главное</h3>
            </div>
            <div class="uk-width-auto">
                <a uk-icon="more-vertical"></a>
                <div uk-dropdown="mode: click; pos: bottom-right; duration: 100">
                    <ul class="uk-nav uk-dropdown-nav uk-iconnav uk-iconnav-vertical">
                        <li>
                            <a href="{% url 'library:statistics' %}">
                                <span uk-icon="file-text" class="uk-margin-small-right"></span>
                                Просмотреть статистику
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'library:book_create' %}">
                                <span uk-icon="plus" class="uk-margin-small-right"></span>
                                Добавить книгу
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="uk-card-body">
        <ul class="uk-list">
            <li>
                <a href="{% url 'library:book_list' %}">Все книги</a>
                <span class="uk-text-meta">{{ books_count }}</span>
            </li>
            {% for tag in tags %}
                <li>
                    <span class="uk-icon" uk-icon="hashtag"></span>
                    <a href="{% url 'library:tag_book_list' tag.id %}">
                        <span class="tag {{ tag.color }} uk-text-small">{{ tag }}</span>
                    </a>
                    <span class="uk-text-meta">{{ tag.book__count }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>