apps/blog/urls.py
from django.urls import re_path
from .views import *

urlpatterns = [
    re_path(
        route=r'^(?P<page>\d*)?/?$',
        view=PostListView.as_view(),
        name='post_list'
    ),
    re_path(
        route=r'^category/(?P<category>\d+)/(?P<page>\d*)?/?$',
        view=CategoryPostListView.as_view(),
        name='category_post_list'
    ),
    re_path(
        route=r'^post/(?P<pk>\d+)/$',
        view=PostDetailView.as_view(),
        name='post_detail'
    ),
    re_path(
        route=r'^post/(?P<pk>\d+)/edit/$',
        view=PostUpdateView.as_view(),
        name='post_edit'
    ),
    re_path(
        route=r'^post/add/$',
        view=PostCreateView.as_view(),
        name='post_add'
    ),
    re_path(
        route=r'^post/(?P<pk>\d+)/delete/$',
        view=PostDeleteView.as_view(),
        name='post_delete'
    ),
     re_path(
        route=r'^categories/$',
        view=CategoryListView.as_view(),
        name='category_list'
    ),
    re_path(
        route=r'^category/add/$',
        view=CategoryCreateView.as_view(),
        name='category_add'
    ),
    re_path(
        route=r'^category/(?P<pk>\d+)/edit/$',
        view=CategoryUpdateView.as_view(),
        name='category_edit'
    ),
    re_path(
        route=r'^comment/(?P<pk>\d+)/delete/$',
        view=CommentDeleteView.as_view(),
        name='comment_delete'
    ),
]

urls.py
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    re_path(r'^', include(('apps.blog.urls', 'blog'), namespace='blog')),
    re_path(r'^', include(('apps.personal_area.urls', 'personal_area'), namespace='personal_area')),
    path("films/", include(('apps.films.urls', 'films'), namespace='films')),
    re_path(r'^library/', include(('apps.library.urls', 'library'), namespace='library')),
    re_path(r'^summernote/', include('django_summernote.urls')),
    re_path(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/blog/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse
from apps.personal_area.models import Like


class Category(models.Model):
    title = models.CharField(verbose_name="Название", max_length=255)

    def get_absolute_url(self):
        return reverse('blog:category_post_list', args=(self.id,))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Tag(models.Model):
    name = models.CharField(verbose_name="Название", max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"


class Post(models.Model):
    category = models.ForeignKey(verbose_name="Категория", to='Category', on_delete=models.CASCADE)
    title = models.CharField(verbose_name="Заголовок", max_length=255)
    description = models.TextField(verbose_name="Описание", blank=True)
    text = models.TextField(verbose_name="Текст")
    slug = models.SlugField(help_text="Строка используемая для формирования url адреса на пост")
    tags = models.ManyToManyField(verbose_name="Теги", to='Tag', blank=True)
    create_date = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)
    change_date = models.DateTimeField(verbose_name="Дата последнего изменения", auto_now=True)
    draft = models.BooleanField(verbose_name="Черновик", default=False)
    author = models.ForeignKey(verbose_name="Автор", to='auth.User', on_delete=models.CASCADE)
    likes = GenericRelation(to='personal_area.Like', related_query_name='posts')
    comments = GenericRelation(to='personal_area.Comment', related_query_name='posts')

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.id,))

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-create_date',)
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

apps/blog/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from .models import Post, Category


class PostFormAdmin(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        widgets = {
            'text': SummernoteWidget(),
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'category', 'slug', 'description', 'text', 'tags', 'draft',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'uk-input uk-form-width-large'}),
            'category': forms.Select(attrs={'class': 'uk-select uk-form-width-large'}),
            'slug': forms.TextInput(attrs={'class': 'uk-input uk-form-width-large'}),
            'description': forms.Textarea(attrs={'rows': 5, 'class': 'uk-input uk-form-width-large'}),
            'text': SummernoteWidget(),
            'tags': forms.SelectMultiple(attrs={'class': 'uk-select uk-form-width-large'}),
            'draft': forms.CheckboxInput(attrs={'class': 'uk-checkbox'}),
        }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'uk-input uk-form-width-large'}),
        }

apps/blog/views.py
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin, ProcessFormView
from django.contrib.auth.mixins import UserPassesTestMixin, PermissionRequiredMixin
from django.db.models import Q

from apps.personal_area.forms import CommentForm
from apps.personal_area.models import Comment
from apps.blog.filterset import PostFilterSet
from .models import *
from .forms import *


class PostListView(ListView):
    template_name = 'blog/post_list.html'
    model = Post
    paginate_by = 10
    filterset_class = PostFilterSet

    def get_queryset(self):
        queryset = super(PostListView, self).get_queryset()
        if self.request.user.is_superuser:
            return queryset
        if self.request.user.is_anonymous:
            return queryset.exclude(draft=True)
        return queryset.filter(Q(draft=False) | Q(author=self.request.user))


class CategoryPostListView(PostListView):
    template_name = 'blog/post_list_category.html'
    category = None

    def get_queryset(self):
        queryset = super(CategoryPostListView, self).get_queryset()
        self.category = Category.objects.get(id=self.kwargs['category'])
        queryset = queryset.filter(category=self.category)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CategoryPostListView, self).get_context_data(**kwargs)
        context['category'] = self.category
        return context


class PostDetailView(DetailView, UserPassesTestMixin, ProcessFormView, FormMixin):
    template_name = 'blog/post_detail.html'
    model = Post
    form_class = CommentForm

    def test_func(self):
        if self.request.user.is_superuser:
            return True
        obj = self.get_object()
        if obj.draft and obj.author == self.request.user:
            return True
        return not obj.draft

    def get_success_url(self):
        return self.get_object().get_absolute_url()

    def form_valid(self, form):
        obj = self.get_object()
        comment = form.save(commit=False)
        comment.content_object = obj
        comment.author = self.request.user
        comment.save()
        return super(PostDetailView, self).form_valid(form)


class PostUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'blog/post_update.html'
    model = Post
    form_class = PostForm
    permission_required = ['blog.change_post']


class PostCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'blog/post_create.html'
    model = Post
    form_class = PostForm
    permission_required = ['blog.create_post']
    object = None

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class PostDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'blog/post_delete.html'
    model = Post
    permission_required = ['blog.delete_post']

    def get_success_url(self):
        return reverse('blog:post_list')


class CategoryCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'blog/category_create.html'
    model = Category
    form_class = CategoryForm
    permission_required = ['blog.create_category']


class CategoryUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'blog/category_update.html'
    model = Category
    form_class = CategoryForm
    permission_required = ['blog.change_category']


class CommentDeleteView(UserPassesTestMixin, DeleteView):
    model = Comment

    def test_func(self):
        if self.get_object().author == self.request.user or self.request.user.is_superuser:
            return True
        return False

    def get_success_url(self):
        obj = self.get_object()
        return reverse('blog:post_detail', args=(obj.content_object.id,))


class CategoryListView(ListView):
    template_name = 'blog/category_list.html'
    model = Category

apps/blog/templates/blog/category_create.html
{% extends 'blog/category_update.html' %}

{% block breadcrumb %}
    <li><a href="{% url 'blog:post_list' %}">Все посты</a></li>
    <li><span>Создание категории</span></li>
{% endblock %}

{% block card_title %}Создание категории{% endblock %}

apps/blog/templates/blog/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block breadcrumb %}
    <li><a href="{% url 'blog:post_list' %}">Все посты</a></li>
    <li><span>Дерево категорий</span></li>
{% endblock %}

{% block content %}
    <div class="uk-card uk-card-default uk-width-2-3@m">
        <div class="uk-card-header">
            <div class="uk-width-expand">
                <h3 class="uk-card-title uk-margin-remove-bottom">
                    Список категорий
                </h3>
            </div>
        </div>
        <div class="uk-card-body">
            <ul class="uk-list uk-list-primary">
                {% for category in category_list %}
                    <li>
                        <span uk-icon="icon: folder"></span>
                        <a class="uk-link-heading" href="{{ category.get_absolute_url }}">
                            {{category}}
                        </a>
                        <table class="uk-table uk-table-divider uk-table-small uk-table-hover uk-margin-left">
                            {% for post in category.post_set.all %}
                                {% if request.user.is_superuser or not post.draft  %}
                                    <tr>
                                        <td>
                                            <span uk-icon="icon: file-text"></span>
                                            <a class="uk-link-heading" href="{{ post.get_absolute_url }}">
                                                {{post}}
                                            </a>
                                        </td>
                                        <td align="right">{{post.create_date | date:"Y-m-d H:i"}}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </table>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="uk-card-footer">
        </div>
    </div>
{% endblock %}

apps/blog/templates/blog/category_sidebar.html
<div class="uk-card uk-card-default uk-margin">
    <div class="uk-card-header">
        <div uk-grid>
            <div class="uk-width-expand">
                <h3 class="uk-card-title uk-margin-remove-bottom">Категории</h3>
            </div>
            <div class="uk-width-auto">
                <a uk-icon="more-vertical"></a>
                <div uk-dropdown="mode: click; pos: bottom-right; duration: 100">
                    <ul class="uk-nav uk-dropdown-nav uk-iconnav uk-iconnav-vertical">
                        <li>
                            <a href="{% url 'blog:post_add' %}">
                                <span uk-icon="plus" class="uk-margin-small-right"></span>
                                Создать пост
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'blog:category_add' %}">
                                <span uk-icon="plus" class="uk-margin-small-right"></span>
                                Создать категорию
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="uk-card-body">
        <ul class="uk-nav-default" uk-nav>
            <li>
                <a href="{% url 'blog:post_list' %}">
                    <span class="uk-margin-small-right" uk-icon="icon: folder"></span>
                    Все посты
                </a>
            </li>
            {% for category in categories %}
                <li>
                    <a href="{{ category.get_absolute_url }}">
                        <span class="uk-margin-small-right" uk-icon="icon: folder"></span>
                        {{ category }}
                        <span class="uk-badge uk-text-secondary uk-background-muted">
                            {{ category.post_set.count }}
                        </span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="uk-card-footer">
        <ul class="uk-nav-default" uk-nav>
            <li>
                <a href="{% url 'blog:category_list' %}">
                    <span uk-icon="list" class="uk-margin-small-right"></span>
                    Дерево категорий
                </a>
            </li>
        </ul>
    </div>
</div>

apps/blog/templates/blog/category_update.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li><a href="{% url 'blog:post_list' %}">Все посты</a></li>
    <li><span>Редактирование категории</span></li>
{% endblock %}

{% block content %}
    <div class="uk-card uk-card-default">
        <div class="uk-card-header">
            <div class="uk-grid-small uk-flex-middle" uk-grid>
                <div class="uk-width-expand">
                    <h3 class="uk-card-title uk-margin-remove-bottom">
                        {% block card_title %}Редактирование категории{% endblock %}
                    </h3>
                </div>
            </div>
        </div>
        <div class="uk-card-body">
            <form method="post" class="uk-form-horizontal">
                {% csrf_token %}

                {% if form.non_field_errors %}
                    <div class="uk-text-danger">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}

                {% include 'blog/form_field.html' with field=form.title %}

                <div class="uk-margin">
                    <button type="submit" class="uk-button uk-button-primary">
                        Сохранить
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

apps/blog/templates/blog/form_field.html
<div class="uk-margin">
    <label for="{{ field.id_for_label }}" class="uk-form-label">
        {{ field.label }}
        {% if field.field.required %}
            <span class="uk-text-danger">*</span>
        {% endif %}
    </label>
    <div class="uk-form-controls">
        {{ field }}
        {% if field.help_text %}
            <div class="uk-text-meta">
                {{ field.help_text|safe }}
            </div>
        {% endif %}
        {% if field.errors %}
            <div class="uk-text-danger">
                {{ field.errors }}
            </div>
        {% endif %}
    </div>
</div>

apps/blog/templates/blog/pagination.html
<ul class="uk-pagination uk-flex-center" uk-margin>
    {% if page_obj.has_previous %}
        <li>
            <a href="{% url 'blog:post_list' page_obj.previous_page_number %}?{{ request.GET.urlencode }}">
                <span uk-pagination-previous></span>
            </a>
        </li>
    {% else %}
        <li class="uk-disabled">
            <a href="#">
                <span uk-pagination-previous></span>
            </a>
        </li>
    {% endif %}
    {% for page_num in paginator.page_range %}
        {% if page_num == page_obj.number %}
            <li class="uk-active">
                <span>{{ page_num }}</span>
            </li>
        {% else %}
            <li>
                <a href="{% url 'blog:post_list' page_num %}?{{ request.GET.urlencode }}">{{ page_num }}</a>
            </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li>
            <a href="{% url 'blog:post_list' page_obj.next_page_number %}?{{ request.GET.urlencode }}">
                <span uk-pagination-next></span>
            </a>
        </li>
    {% else %}
        <li class="uk-disabled">
            <a href="#">
                <span uk-pagination-next></span>
            </a>
        </li>
    {% endif %}
</ul>

apps/blog/templates/blog/pagination_category.html
<ul class="uk-pagination uk-flex-center" uk-margin>
    {% if page_obj.has_previous %}
        <li>
            <a href="{% url 'blog:category_post_list' category.id page_obj.previous_page_number %}?{{ request.GET.urlencode }}">
                <span uk-pagination-previous></span>
            </a>
        </li>
    {% else %}
        <li class="uk-disabled">
            <a href="#">
                <span uk-pagination-previous></span>
            </a>
        </li>
    {% endif %}
    {% for page_num in paginator.page_range %}
        {% if page_num == page_obj.number %}
            <li class="uk-active">
                <span>{{ page_num }}</span>
            </li>
        {% else %}
            <li>
                <a href="{% url 'blog:category_post_list' category.id page_num %}?{{ request.GET.urlencode }}">{{ page_num }}</a>
            </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li>
            <a href="{% url 'blog:category_post_list' category.id page_obj.next_page_number %}?{{ request.GET.urlencode }}">
                <span uk-pagination-next></span>
            </a>
        </li>
    {% else %}
        <li class="uk-disabled">
            <a href="#">
                <span uk-pagination-next></span>
            </a>
        </li>
    {% endif %}
</ul>

apps/blog/templates/blog/post_create.html
{% extends 'blog/post_update.html' %}

{% block breadcrumb %}
    <li><a href="{% url 'blog:post_list' %}">Все посты</a></li>
    <li><span>Создание</span></li>
{% endblock %}

{% block card_title %}Создание{% endblock %}

apps/blog/templates/blog/post_delete.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li><a href="{% url 'blog:post_list' %}">Все посты</a></li>
    <li><a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></li>
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    <li><span>Удаление</span></li>
{% endblock %}

{% block content %}
    <div class="uk-card uk-card-default uk-width-2-3@m">
        <div class="uk-card-header">
            <div class="uk-grid-small uk-flex-middle" uk-grid>
                <div class="uk-width-expand">
                    <h3 class="uk-card-title uk-margin-remove-bottom">Удаление</h3>
                </div>
            </div>
        </div>
        <div class="uk-card-body">
            <p>
                Информация о посте
            </p>
            <table class="uk-table uk-table-divider">
                <tbody>
                <tr>
                    <th>Заголовок</th>
                    <td>{{ post.title }}</td>
                </tr>
                <tr>
                    <th>Дата создания</th>
                    <td>{{ post.create_date }}</td>
                </tr>
                <tr>
                    <th>Дата последнего изменения</th>
                    <td>{{ post.change_date }}</td>
                </tr>
                <tr>
                    <th>Количество комментариев</th>
                    <td>{{ post.comments.count }}</td>
                </tr>
                <tr>
                    <th>Количество лайков</th>
                    <td>{{ post.likes.count }}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="uk-card-footer">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="uk-button uk-button-danger">
                    Удалить
                </button>
            </form>
        </div>
    </div>
{% endblock %}

apps/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block breadcrumb %}
    <li><a href="{% url 'blog:post_list' %}">Все посты</a></li>
    <li><a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></li>
    <li><span>{{ post.title }}</span></li>
{% endblock %}

{% block content %}
    <div class="uk-card uk-card-default uk-width-2-3@m">
        <div class="uk-card-header">
            <div class="uk-grid-small uk-flex-middle" uk-grid>
                <div class="uk-width-expand">
                    <h3 class="uk-card-title uk-margin-remove-bottom">
                        {{ post.title }}
                        {% if post.draft %}
                            <div class="uk-label uk-label-warning">Draft</div>
                        {% endif %}
                    </h3>
                    <p class="uk-text-meta uk-margin-remove-top">
                        <time datetime="2016-04-01T19:00">{{ post.create_date }}</time>
                    </p>
                </div>
                <div class="uk-width-auto">
                    <a uk-icon="more-vertical"></a>
                    <div uk-dropdown="mode: click; pos: bottom-right; duration: 100">
                        <ul class="uk-nav uk-dropdown-nav uk-iconnav uk-iconnav-vertical">
                            <li>
                                <a href="{% url 'blog:post_edit' post.id %}">
                                    <span uk-icon="file-edit" class="uk-margin-small-right"></span>
                                    Редактировать
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'blog:post_delete' post.id %}">
                                    <span uk-icon="trash" class="uk-margin-small-right"></span>
                                    Удалить
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="uk-card-body">
            {{ post.text|safe }}
        </div>
        <div class="uk-card-footer">
            {% for like in post.likes.all %}
                <img class="small-avatar uk-border-circle" src="{{ like.user.profile.get_photo_url }}">
            {% endfor %}
        </div>
    </div>

    <ul class="uk-comment-list uk-width-2-3@m uk-padding-small">
        {% for comment in post.comments.all %}
            <li id="comment-{{ comment.id }}">
                <article class="uk-comment uk-visible-toggle">
                    <header class="uk-comment-header uk-position-relative">
                        <div class="uk-grid-medium uk-flex-middle" uk-grid>
                            <div class="uk-width-auto">
                                <img class="uk-comment-avatar uk-border-circle medium-avatar"
                                     src="{{ comment.author.profile.get_photo_url }}"
                                     width="80" height="80" alt="">
                            </div>
                            <div class="uk-width-expand">
                                <h4 class="uk-comment-title uk-margin-remove">
                                    <a class="uk-link-reset" href="#">{{ comment.author }}</a>
                                </h4>
                                <p class="uk-comment-meta uk-margin-remove-top">
                                    <a class="uk-link-reset" href="#">{{ comment.creation_date }}</a>
                                </p>
                            </div>
                        </div>
                        {% if comment.author == request.user or request.user.is_superuser %}
                            <div class="uk-position-top-right uk-position-small uk-hidden-hover">
                                <form method="post" action="{% url 'blog:comment_delete' comment.id %}">
                                    {% csrf_token %}
                                    <button class="uk-link-muted uk-button uk-button-text">
                                        Удалить
                                    </button>
                                </form>
                            </div>
                        {% endif %}
                    </header>
                    <div class="uk-comment-body">
                        {{ comment.text }}
                    </div>
                </article>
            </li>
        {% endfor %}
    </ul>

    {% if not request.user.is_anonymous %}
        <form method="post" class="uk-width-2-3@m">
            {% csrf_token %}
            <div class="uk-margin">
                {{ form.text }}
            </div>
            <button type="submit" class="uk-button uk-button-primary">
                Отправить
            </button>
        </form>
    {% endif %}
{% endblock %}

apps/blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load blog_template_tags %}

{% block breadcrumb %}
    <li><span>Все посты</span></li>
{% endblock %}

{% block content %}
    <div class="uk-child-width-expand" uk-grid>
        <div class="uk-width-1-3@m">
            {% include_category_sidebar %}
        </div>
        <div>
            {% for post in post_list %}
                <div class="uk-card uk-card-default uk-margin">
                    <div class="uk-card-header">
                        <div uk-grid>
                            <div class="uk-width-auto">
                                <img class="uk-comment-avatar uk-border-circle"
                                     src="{{ post.author.profile.get_photo_url }}"
                                     width="60px" height="60px" alt="{{ post.author.username }}">
                            </div>
                            <div class="uk-width-expand">
                                <h3 class="uk-card-title uk-margin-remove-bottom">
                                    {{ post.title }}
                                    {% if post.draft %}
                                        <div class="uk-label uk-label-warning">Draft</div>
                                    {% endif %}
                                </h3>
                                <div class="uk-text-meta">
                                    <div>
                                        <span uk-icon="icon:user; ratio:0.7"></span>
                                        {{ post.author }}
                                        &nbsp;
                                        <span uk-icon="icon:calendar; ratio:0.7"></span>
                                        {{ post.create_date }}
                                    </div>
                                </div>
                            </div>
                            <div class="uk-width-auto">
                                <a uk-icon="more-vertical"></a>
                                <div uk-dropdown="mode: click; pos: bottom-right; duration: 100">
                                    <ul class="uk-nav uk-dropdown-nav">
                                        <li>
                                            <a href="{{ post.get_absolute_url }}">
                                                <span uk-icon="file" class="uk-margin-small-right"></span>
                                                Просмотреть
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'blog:post_edit' post.id %}">
                                                <span uk-icon="file-edit" class="uk-margin-small-right"></span>
                                                Редактировать
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'blog:post_delete' post.id %}">
                                                <span uk-icon="trash" class="uk-margin-small-right"></span>
                                                Удалить
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="uk-card-body">
                        {{ post.description }}
                    </div>
                    <div class="uk-card-footer">
                        <div uk-grid>
                            <div class="uk-width-expand uk-flex uk-flex-left">
                                {% get_like_icon post %}
                                <span>{{ post.likes.count }}</span>
                                {% get_comment_icon post %}
                                {{ post.comments.count }}
                            </div>
                            <div class="uk-width-expand uk-flex uk-flex-right">
                                <a href="{{ post.get_absolute_url }}" class="uk-button uk-button-link">Read more</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="uk-text-center uk-card uk-card-default uk-card-body">
                    Пусто
                </div>
            {% endfor %}
            {% block pagination %}
                {% include 'blog/pagination.html' %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

apps/blog/templates/blog/post_list_category.html
{% extends 'blog/post_list.html' %}

{% block breadcrumb %}
    <li><a href="{% url 'blog:post_list' %}">Все посты</a></li>
    <li><span>{{ category }}</span></li>
{% endblock %}

{% block pagination %}
    {% include 'blog/pagination_category.html' %}
{% endblock %}