apps/personal_area/urls.py
from django.urls import re_path
from .views import *


urlpatterns = [
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),
    re_path(r'^registration/$', RegistrationView.as_view(), name='registration'),
    re_path(r'^profile/$', ProfileView.as_view(), name='profile_detail'),
    re_path(r'^profile/edit/$', ProfileUpdateView.as_view(), name='profile_update'),
    # url(r'^profile/edit/$', UserUpdateView.as_view(), name='profile_update'),
]

urls.py
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    re_path(r'^', include(('apps.blog.urls', 'blog'), namespace='blog')),
    re_path(r'^', include(('apps.personal_area.urls', 'personal_area'), namespace='personal_area')),
    path("films/", include(('apps.films.urls', 'films'), namespace='films')),
    re_path(r'^library/', include(('apps.library.urls', 'library'), namespace='library')),
    re_path(r'^summernote/', include('django_summernote.urls')),
    re_path(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/personal_area/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.templatetags.static import static


class Profile(models.Model):
    user = models.OneToOneField(verbose_name='Пользователь', to='auth.User', on_delete=models.CASCADE)
    photo = models.ImageField(verbose_name='Фото', blank=True)

    def __str__(self):
        return f"Профиль: {self.user}"

    def get_photo_url(self):
        if self.photo and self.photo.url:
            return self.photo.url
        return static('img/default_avatar.jpg')

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class Like(models.Model):
    limit = models.Q(app_label='library', model='book') | models.Q(app_label='blog', model='post')

    user = models.ForeignKey(verbose_name="Пользователь", to='auth.User', on_delete=models.CASCADE)
    creation_date = models.DateTimeField(verbose_name="Дата создания", auto_now=True)

    content_type = models.ForeignKey(to='contenttypes.ContentType', limit_choices_to=limit, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey(ct_field='content_type', fk_field='object_id')

    def __str__(self):
        return str(self.content_type)

    class Meta:
        unique_together = ('user', 'object_id', 'content_type')
        verbose_name = "Лайк"
        verbose_name_plural = "Лайки"


class Comment(models.Model):
    limit = models.Q(app_label='library', model='book') | models.Q(app_label='blog', model='post')

    text = models.TextField(verbose_name="Текст")
    author = models.ForeignKey(verbose_name="Автор", to='auth.User', on_delete=models.CASCADE)
    creation_date = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)

    content_type = models.ForeignKey(to='contenttypes.ContentType', limit_choices_to=limit, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey(ct_field='content_type', fk_field='object_id')

    def __str__(self):
        return str(self.content_type)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

apps/personal_area/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, UsernameField
from django import forms
from .models import Profile, Comment


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'uk-input'


class RegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'uk-input'


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'uk-input uk-form-width-large'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'uk-input uk-form-width-large'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'uk-input uk-form-width-large'}))

    class Meta:
        model = Profile
        fields = ('photo',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={'class': 'uk-textarea', 'rows': 5}),
        }

apps/personal_area/views.py
from django.views.generic import FormView, RedirectView, TemplateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView as BaseLoginView, LogoutView as BaseLogoutView
from .forms import *


class LoginView(BaseLoginView):
    template_name = 'personal_area/login.html'
    authentication_form = LoginForm


class LogoutView(BaseLogoutView):
    next_page = 'blog:post_list'


class RegistrationView(FormView):
    template_name = 'personal_area/registration.html'
    form_class = RegistrationForm
    success_url = '/'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super(RegistrationView, self).form_valid(form)


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'personal_area/profile_detail.html'


class ProfileUpdateView(UpdateView):
    template_name = 'personal_area/profile_update.html'
    form_class = ProfileForm

    def get_object(self, queryset=None):
        if self.request.user.profile:
            return self.request.user.profile

    def get_initial(self):
        user = self.request.user
        initial_data = {
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email,
        }
        return initial_data

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.email = form.cleaned_data['email']
        user.save()
        return super(ProfileUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('personal_area:profile_detail')

apps/personal_area/templates/personal_area/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="uk-flex uk-flex-center">
        <div class="uk-card uk-card-default uk-width-1-2@m">
            <div class="uk-card-header uk-text-center">
                <h3 class="uk-card-title uk-margin-remove-bottom">Авторизация</h3>
            </div>
            <form class="uk-form-horizontal" method="post">
                <div class="uk-card-body">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        <div class="uk-text-danger">
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                    <div class="uk-margin">
                        <label for="{{ form.username.id_for_label }}" class="uk-form-label">
                            {{ form.username.label }}
                        </label>
                        <div class="uk-form-controls">
                            {{ form.username }}
                            <div class="uk-text-meta">
                                {{ form.username.help_text|safe }}
                            </div>
                            {% if form.username.errors %}
                                <div class="uk-text-danger">
                                    {{ form.username.errors }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="uk-margin">
                        <label for="{{ form.password.id_for_label }}" class="uk-form-label">
                            {{ form.password.label }}
                        </label>
                        <div class="uk-form-controls">
                            {{ form.password }}
                            <div class="uk-text-meta">
                                {{ form.password.help_text|safe }}
                            </div>
                            {% if form.password.errors %}
                                <div class="uk-text-danger">
                                    {{ form.password.errors }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="uk-card-footer">
                    <div class="uk-flex uk-flex-between uk-flex-middle">
                        <div>
                            <button class="uk-button uk-button-primary" type="submit">
                                Войти
                            </button>
                        </div>
                        <div class="">
                            <a class="uk-button uk-button-link" href="{% url 'personal_area:registration' %}">
                                Зарегистрироваться
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

apps/personal_area/templates/personal_area/profile_detail.html
{% extends 'base.html' %}
{% load static %}

{% block breadcrumb %}
    <li><span>Профиль</span></li>
{% endblock %}

{% block content %}
    <div class="uk-card uk-card-default">
        <div class="uk-card-header">
            <div class="uk-grid-small uk-flex-middle" uk-grid>
                <div class="uk-width-expand">
                    <h3 class="uk-card-title uk-margin-remove-bottom">
                        {{ user.username }}
                    </h3>
                </div>
                <div class="uk-width-auto">
                    <a uk-icon="more-vertical"></a>
                    <div uk-dropdown="mode: click; pos: bottom-right; duration: 100">
                        <ul class="uk-nav uk-dropdown-nav uk-iconnav uk-iconnav-vertical">
                            <li>
                                <a href="{% url 'personal_area:profile_update' %}">
                                    <span uk-icon="file-edit" class="uk-margin-small-right"></span>
                                    Редактировать
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span uk-icon="trash" class="uk-margin-small-right"></span>
                                    Удалить
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="uk-card-body">
            <div uk-grid>
                <div class="uk-width-1-3@m">
                    <div class="uk-text-center">
                        {% if user.profile and user.profile.photo %}
                            <img src="{{ user.profile.photo.url }}">
                        {% else %}
                            <img src="{% static 'img/default_avatar.jpg' %}">
                        {% endif %}
                    </div>
                </div>
                <div class="uk-width-expand@m">
                    <ul uk-accordion="multiple: true">
                        <li class="uk-open">
                            <a class="uk-accordion-title" href="#">Информация</a>
                            <div class="uk-accordion-content">
                                <table class="uk-table uk-table-divider">
                                    <tbody>
                                    <tr>
                                        <th>Username</th>
                                        <td class="uk-text-right">{{ user.username }}</td>
                                    </tr>
                                    <tr>
                                        <th>E-mail</th>
                                        <td class="uk-text-right">{{ user.email }}</td>
                                    </tr>
                                    <tr>
                                        <th>Имя</th>
                                        <td class="uk-text-right">{{ user.first_name }}</td>
                                    </tr>
                                    <tr>
                                        <th>Фамилия</th>
                                        <td class="uk-text-right">{{ user.last_name }}</td>
                                    </tr>
                                    <tr>
                                        <th>Дата регистрации</th>
                                        <td class="uk-text-right">{{ user.date_joined }}</td>
                                    </tr>
                                    <tr>
                                        <th>Последнего входа</th>
                                        <td class="uk-text-right">{{ user.last_login }}</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </li>
                        <li>
                            <a class="uk-accordion-title" href="#">Комментарии</a>
                            <div class="uk-accordion-content">
                                <div class="uk-margin">Всего комментариев {{ user.comment_set.count }}</div>
                                <ul class="uk-list">
                                    {% for comment in user.comment_set.all %}
                                        <li>
                                            <span uk-icon="comment" style="color: blue"></span>
                                            <span class="uk-text-meta">{{ comment.creation_date }}</span>
                                            {{ comment.content_type }}:
                                            <a href="{{ comment.content_object.get_absolute_url }}">
                                                {{ comment.content_object }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="uk-accordion-title" href="#">Лайки</a>
                            <div class="uk-accordion-content">
                                <div class="uk-margin">Всего лайков {{ user.like_set.count }}</div>
                                <ul class="uk-list">
                                    {% for like in user.like_set.all %}
                                        <li>
                                            <span uk-icon="heart" style="color: red"></span>
                                            <span class="uk-text-meta">{{ like.creation_date }}</span>
                                            {{ like.content_type }}:
                                            <a href="{{ like.content_object.get_absolute_url }}">
                                                {{ like.content_object }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/personal_area/templates/personal_area/profile_update.html
{% extends 'base.html' %}
{% load static %}

{% block breadcrumb %}
    <li><a href="{% url 'personal_area:profile_detail' %}">Профиль</a></li>
    <li><span>Редактирование</span></li>
{% endblock %}

{% block content %}
    <div class="uk-card uk-card-default">
        <div class="uk-card-header">
            <div class="uk-grid-small uk-flex-middle" uk-grid>
                <div class="uk-width-expand">
                    <h3 class="uk-card-title uk-margin-remove-bottom">
                        {{ user.username }}
                    </h3>
                </div>
                <div class="uk-width-auto">
                    <a uk-icon="more-vertical"></a>
                    <div uk-dropdown="mode: click; pos: bottom-right; duration: 100">
                        <ul class="uk-nav uk-dropdown-nav uk-iconnav uk-iconnav-vertical">
                            <li>
                                <a href="{% url 'personal_area:profile_update' %}">
                                    <span uk-icon="file-edit" class="uk-margin-small-right"></span>
                                    Редактировать
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span uk-icon="trash" class="uk-margin-small-right"></span>
                                    Удалить
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="uk-card-body">
            <form class="uk-form-horizontal" method="post" enctype="multipart/form-data">
                <div uk-grid>
                    <div class="uk-width-1-3@m">
                        <div class="uk-text-center">
                            {% if user.profile and user.profile.photo %}
                                <img src="{{ user.profile.photo.url }}">
                            {% else %}
                                <img src="{% static 'img/default_avatar.jpg' %}">
                            {% endif %}
                            <div>
                                {{ form.photo }}
                            </div>
                        </div>
                    </div>
                    <div class="uk-width-expand@m">
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            <div class="uk-text-danger">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}
                        <div class="uk-margin">
                            <label for="{{ form.first_name.id_for_label }}" class="uk-form-label">
                                {{ form.first_name.label }}
                            </label>
                            <div class="uk-form-controls">
                                {{ form.first_name }}
                                <div class="uk-text-meta">
                                    {{ form.first_name.help_text|safe }}
                                </div>
                                {% if form.first_name.errors %}
                                    <div class="uk-text-danger">
                                        {{ form.first_name.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="uk-margin">
                            <label for="{{ form.last_name.id_for_label }}" class="uk-form-label">
                                {{ form.last_name.label }}
                            </label>
                            <div class="uk-form-controls">
                                {{ form.last_name }}
                                <div class="uk-text-meta">
                                    {{ form.last_name.help_text|safe }}
                                </div>
                                {% if form.last_name.errors %}
                                    <div class="uk-text-danger">
                                        {{ form.last_name.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="uk-margin">
                            <label for="{{ form.email.id_for_label }}" class="uk-form-label">
                                {{ form.email.label }}
                            </label>
                            <div class="uk-form-controls">
                                {{ form.email }}
                                <div class="uk-text-meta">
                                    {{ form.email.help_text|safe }}
                                </div>
                                {% if form.email.errors %}
                                    <div class="uk-text-danger">
                                        {{ form.email.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <button class="uk-button uk-button-primary" type="submit">
                            Сохранить
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

apps/personal_area/templates/personal_area/registration.html
{% extends 'base.html' %}

{% block content %}
    <div class="uk-flex uk-flex-center">
        <div class="uk-card uk-card-default uk-width-1-2@m">
            <div class="uk-card-header uk-text-center">
                <h3 class="uk-card-title uk-margin-remove-bottom">Регистрация</h3>
            </div>
            <form class="uk-form-horizontal" method="post">
                <div class="uk-card-body">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        <div class="uk-text-danger">
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                    <div class="uk-margin">
                        <label for="{{ form.username.id_for_label }}" class="uk-form-label">
                            {{ form.username.label }}
                        </label>
                        <div class="uk-form-controls">
                            {{ form.username }}
                            <div class="uk-text-meta">
                                {{ form.username.help_text|safe }}
                            </div>
                            {% if form.username.errors %}
                                <div class="uk-text-danger">
                                    {{ form.username.errors }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="uk-margin">
                        <label for="{{ form.password1.id_for_label }}" class="uk-form-label">
                            {{ form.password1.label }}
                        </label>
                        <div class="uk-form-controls">
                            {{ form.password1 }}
                            <div class="uk-text-meta">
                                {{ form.password1.help_text|safe }}
                            </div>
                            {% if form.password1.errors %}
                                <div class="uk-text-danger">
                                    {{ form.password1.errors }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="uk-margin">
                        <label for="{{ form.password2.id_for_label }}" class="uk-form-label">
                            {{ form.password2.label }}
                        </label>
                        <div class="uk-form-controls">
                            {{ form.password2 }}
                            <div class="uk-text-meta">
                                {{ form.password2.help_text|safe }}
                            </div>
                            {% if form.password2.errors %}
                                <div class="uk-text-danger">
                                    {{ form.password2.errors }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="uk-card-footer">
                    <div class="uk-flex uk-flex-between uk-flex-middle">
                        <div>
                            <button class="uk-button uk-button-primary" type="submit">
                                Зарегистрироваться
                            </button>
                        </div>
                        <div class="">
                            <a class="uk-button uk-button-link" href="{% url 'personal_area:login' %}">
                                Войти
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}