apps/blog/urls.py
from django.urls import re_path
from .views import *

urlpatterns = [
    re_path(
        route=r'^(?P<page>\d*)?/?$',
        view=PostListView.as_view(),
        name='post_list'
    ),
    re_path(
        route=r'^category/(?P<category>\d+)/(?P<page>\d*)?/?$',
        view=CategoryPostListView.as_view(),
        name='category_post_list'
    ),
    re_path(
        route=r'^post/(?P<pk>\d+)/$',
        view=PostDetailView.as_view(),
        name='post_detail'
    ),
    re_path(
        route=r'^post/(?P<pk>\d+)/edit/$',
        view=PostUpdateView.as_view(),
        name='post_edit'
    ),
    re_path(
        route=r'^post/add/$',
        view=PostCreateView.as_view(),
        name='post_add'
    ),
    re_path(
        route=r'^post/(?P<pk>\d+)/delete/$',
        view=PostDeleteView.as_view(),
        name='post_delete'
    ),
     re_path(
        route=r'^categories/$',
        view=CategoryListView.as_view(),
        name='category_list'
    ),
    re_path(
        route=r'^category/add/$',
        view=CategoryCreateView.as_view(),
        name='category_add'
    ),
    re_path(
        route=r'^category/(?P<pk>\d+)/edit/$',
        view=CategoryUpdateView.as_view(),
        name='category_edit'
    ),
    re_path(
        route=r'^comment/(?P<pk>\d+)/delete/$',
        view=CommentDeleteView.as_view(),
        name='comment_delete'
    ),
]

apps/films/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path(
        route="",
        view=FilmListView.as_view(),
        name='films-list'
    ),
    path(
        route="add/",
        view=AddFilmFormView.as_view(),
        name='film-add'
    ),
    path(
        route="<str:pk>/",
        view=FilmDetailView.as_view(),
        name='film-detail'
    ),
    path(
        route="<int:pk>/edit/",
        view=EditFilmFormView.as_view(),
        name='film-edit'
    ),
]

apps/library/urls.py
from django.urls import re_path
from .views import *

urlpatterns = [
    re_path(
        route=r'^(?P<page>\d*)?/?$',
        view=BookListView.as_view(),
        name='book_list'
    ),
    re_path(
        route=r'^tag/(?P<tag>\d+)/(?P<page>\d*)?/?$',
        view=TagBookListView.as_view(),
        name='tag_book_list'
    ),
    re_path(
        route=r'^book/(?P<pk>\d+)/$',
        view=BookDetailView.as_view(),
        name='book_detail'
    ),
    re_path(
        route=r'^book/(?P<pk>\d+)/edit/$',
        view=BookUpdateView.as_view(),
        name='book_edit'
    ),
    re_path(
        route=r'^book/add/$',
        view=BookCreateView.as_view(),
        name='book_create'
    ),
    re_path(
        route=r'^book/(?P<pk>\d+)/delete/$',
        view=BookDeleteView.as_view(),
        name='book_delete'
    ),
    re_path(
        route=r'^comment/(?P<pk>\d+)/delete/$',
        view=CommentDeleteView.as_view(),
        name='comment_delete'
    ),
    re_path(
        route=r'^statistics/$',
        view=StatisticsView.as_view(),
        name='statistics'
    )
]

apps/personal_area/urls.py
from django.urls import re_path
from .views import *


urlpatterns = [
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),
    re_path(r'^registration/$', RegistrationView.as_view(), name='registration'),
    re_path(r'^profile/$', ProfileView.as_view(), name='profile_detail'),
    re_path(r'^profile/edit/$', ProfileUpdateView.as_view(), name='profile_update'),
    # url(r'^profile/edit/$', UserUpdateView.as_view(), name='profile_update'),
]

urls.py
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    re_path(r'^', include(('apps.blog.urls', 'blog'), namespace='blog')),
    re_path(r'^', include(('apps.personal_area.urls', 'personal_area'), namespace='personal_area')),
    path("films/", include(('apps.films.urls', 'films'), namespace='films')),
    re_path(r'^library/', include(('apps.library.urls', 'library'), namespace='library')),
    re_path(r'^summernote/', include('django_summernote.urls')),
    re_path(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>{% block title %}Easy Code{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/uikit.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/themes/github.css' %}">
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">
    <script src="{% static 'js/uikit.min.js' %}"></script>
    <script src="{% static 'js/uikit-icons.min.js' %}"></script>
    <script src="{% static 'js/rainbow-custom.min.js' %}"></script>
    <script src="{% static 'js/Chart.bundle.min.js' %}"></script>
</head>
<body>
<div id="sidebar_menu" uk-offcanvas>
    <div class="uk-offcanvas-bar">
        <button class="uk-offcanvas-close" type="button" uk-close></button>
        <span class="uk-nav-header">Меню</span>
        <ul class="uk-nav uk-nav-default uk-margin-right">
            {% if user.is_anonymous %}
                <li>
                    <a href="{% url 'personal_area:login' %}">
                        <span class="uk-margin-small-right" uk-icon="sign-in"></span>
                        Вход
                    </a>
                </li>
                <li>
                    <a href="{% url 'personal_area:registration' %}">
                        <span class="uk-margin-small-right" uk-icon="sign-in"></span>
                        Регистрация
                    </a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'personal_area:profile_detail' %}">
                        <span class="uk-margin-small-right" uk-icon="user"></span>
                        Профиль
                    </a>
                </li>
                <li>
                    <a href="{% url 'personal_area:logout' %}">
                        <span class="uk-margin-small-right" uk-icon="sign-out"></span>
                        Выход
                    </a>
                </li>
            {% endif %}
            <li class="uk-nav-divider"></li>
            <li>
                <a href="{% url 'blog:post_list' %}">
                    <span class="uk-margin-small-right" uk-icon="folder"></span>
                    Блог
                </a>
            </li>
            <li>
                <a href="{% url 'library:book_list' %}">
                    <span class="uk-margin-small-right" uk-icon="folder"></span>
                    Книги
                </a>
            </li>
            {% if user.is_superuser %}
                <li>
                    <a href="{% url 'films:films-list' %}">
                        <span class="uk-margin-small-right" uk-icon="folder"></span>
                        Фильмы
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>

<div class="uk-section-primary">
    <nav class="uk-navbar-container uk-navbar-transparent">
        <div class="uk-container uk-container-expand">
            <div uk-navbar>
                <div class="uk-navbar-left">
                    <ul class="uk-navbar-nav">
                        <li class="uk-active">
                            <a href="#sidebar_menu" uk-toggle>
                                <span uk-icon="menu"></span>
                            </a>
                        </li>
                        <li class="uk-active">
                            <a href="{% url 'blog:post_list' %}">Easy Code</a>
                        </li>
                    </ul>
                </div>
                <div class="uk-navbar-right">
                    <div>
                        <a class="uk-navbar-toggle" href uk-search-icon></a>
                        <div class="uk-drop" uk-drop="mode: click; pos: left-center; offset: 0">
                            <form class="uk-search uk-search-navbar" method="get" action="">
                                <input name="search" class="uk-search-input" type="search" placeholder="Поиск" aria-label="Поиск" autofocus>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

<div class="uk-container uk-align-center">
    <ul class="uk-breadcrumb uk-overflow-auto">
        {% block breadcrumb %}
        {% endblock %}
    </ul>
</div>

<div class="uk-container uk-align-center">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>